name: tests
on: push
jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v1
    - name: build env
      run: |
        eval "$(conda shell.bash hook)"
        conda create -p ./env \
          --file requirements.txt \
          --file optional-requirements.txt \
          --file test-requirements.txt \
          --channel conda-forge \
          --channel bioconda \
          --strict-channel-priority

        python setup.py sdist && pip install dist/*.tar.gz
    - name: confirm script installed correctly
      run: |
        eval "$(conda shell.bash hook)" && conda activate ./env
        termseq_peaks -h

    - name: run example date
      run: |
        eval "$(conda shell.bash hook)" && conda activate ./env
        (cd peaklib/test && bash test.sh)
